# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scenario_info_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import subprocess
import sys
import os

class Ui_MainWindow(object):
    def button_clicked(self):
        try:
            # Command to start the CARLA simulator (adjust path as needed)
            # subprocess.Popen(['./CarlaUE4.sh'], cwd='/home/sumaiya/carla')  # On Linux or MacOS
            # subprocess.Popen(['CarlaUE4.exe'], cwd='D:\\CARLA_0.9.15\\WindowsNoEditor')  # On Windows
            
            # result = subprocess.run(['python', 'D:\\CARLA_0.9.15\\client\\Carla_project-v2\\CARLA_client\\main.py'], capture_output=True, text=True)
            result = subprocess.run(['python', '/home/sumaiya/carla/Carla_project_v2/CARLA_client/main.py'], capture_output=True, text=True)

            if result.stdout:
                print("Output of carla_api_script.py:", result.stdout)
            if result.stderr:
                print("Error in carla_api_script.py:", result.stderr)
            
            QMessageBox.information(self, 'Success', 'CARLA API Script executed.')
        except Exception as e:
            QMessageBox.critical(self, 'Error', f'Failed to run CARLA API script: {e}')
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 80, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 30, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(260, 190, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(260, 250, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 136, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(260, 130, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 340, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button_clicked)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ScenarioInfoManager"))
        self.label.setText(_translate("MainWindow", "Ego Vehicle Position"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose Position"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Intersection"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Subject Lane"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Left Lane"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Right Lane"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Opposite Lane"))
        self.label_2.setText(_translate("MainWindow", "Road Type"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Choose Road Type"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Motorway"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Expressway"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "local Road"))
        self.label_3.setText(_translate("MainWindow", "Weather Condition"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Choose Weather Condition"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Clear"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Cloudy"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Light Rain"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Moderate Rain"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Heavy Rain"))
        self.label_5.setText(_translate("MainWindow", "Time of Day"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Choose Time of Day"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Day time"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Evening"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Night time"))
        self.label_7.setText(_translate("MainWindow", "Emergency Vehicle Position"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Choose Lane"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Intersection"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Subject Lane"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Left Lane"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Right Lane"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "Opposite Lane"))
        self.pushButton.setText(_translate("MainWindow", "Start Simulation"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
